/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RawMaterial = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'size' : IDL.Text,
  'currentRate' : IDL.Float64,
  'grade' : IDL.Text,
  'materialType' : IDL.Text,
  'weightPerMeter' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [RawMaterial],
      [],
    ),
  'deleteMaterial' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getMaterial' : IDL.Func([IDL.Text], [RawMaterial], ['query']),
  'getMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
  'updateMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [RawMaterial],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RawMaterial = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'size' : IDL.Text,
    'currentRate' : IDL.Float64,
    'grade' : IDL.Text,
    'materialType' : IDL.Text,
    'weightPerMeter' : IDL.Float64,
  });
  
  return IDL.Service({
    'addMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [RawMaterial],
        [],
      ),
    'deleteMaterial' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getMaterial' : IDL.Func([IDL.Text], [RawMaterial], ['query']),
    'getMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
    'updateMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [RawMaterial],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };